# Generated by Django 5.0.4 on 2024-04-19 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('location_name', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('tz_id', models.CharField(max_length=50, null=True)),
                ('localtime_epoch', models.BigIntegerField(null=True)),
                ('localtime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('sleep_id', models.AutoField(primary_key=True, serialize=False)),
                ('sleep_time', models.DateTimeField()),
                ('sleep_duration', models.IntegerField()),
                ('sleep_quality', models.CharField(max_length=10)),
                ('sleep_score', models.IntegerField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.person')),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapi.station')),
            ],
        ),
        migrations.CreateModel(
            name='Noise',
            fields=[
                ('noise_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('noise', models.FloatField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.station')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherAPI',
            fields=[
                ('weather_api_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(null=True)),
                ('last_updated_epoch', models.BigIntegerField(null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('temp_c', models.FloatField(null=True)),
                ('temp_f', models.FloatField(null=True)),
                ('is_day', models.BooleanField(null=True)),
                ('condition_text', models.CharField(max_length=100, null=True)),
                ('condition_icon', models.URLField(null=True)),
                ('condition_code', models.IntegerField(null=True)),
                ('precip_mm', models.FloatField(null=True)),
                ('precip_in', models.FloatField(null=True)),
                ('humidity', models.IntegerField(null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.station')),
            ],
        ),
    ]
