# Generated by Django 5.0.4 on 2024-04-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sleep',
            old_name='person_id',
            new_name='person',
        ),
    ]
