# Generated by Django 5.0.4 on 2024-04-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_rename_person_id_sleep_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleep',
            name='sleep_quality',
        ),
        migrations.AddField(
            model_name='sleep',
            name='sleep_comments',
            field=models.CharField(default='No comments', max_length=255),
        ),
        migrations.AlterField(
            model_name='noise',
            name='noise_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='localtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='localtime_epoch',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='location_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='tz_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weatherapi',
            name='condition_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weatherapi',
            name='condition_icon',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='weatherapi',
            name='condition_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherapi',
            name='humidity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weatherapi',
            name='is_day',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='weatherapi',
            name='last_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='weatherapi',
            name='last_updated_epoch',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='weatherapi',
            name='precip_in',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherapi',
            name='precip_mm',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherapi',
            name='temp_c',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherapi',
            name='temp_f',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherapi',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='weatherapi',
            name='weather_api_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
