# Generated by Django 5.0.4 on 2024-04-19 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_remove_sleep_sleep_quality_sleep_sleep_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.station'),
        ),
    ]
