# Generated by Django 5.0.4 on 2024-04-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_person_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoiseStation',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('noise', models.FloatField()),
                ('location_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('tz_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('weather_api_id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('temp_c', models.FloatField()),
                ('condition_text', models.CharField(max_length=100)),
                ('precip_mm', models.FloatField()),
                ('humidity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sleep',
            name='station',
        ),
        migrations.RemoveField(
            model_name='weatherapi',
            name='station',
        ),
        migrations.AddField(
            model_name='sleep',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleep',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Noise',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.DeleteModel(
            name='WeatherAPI',
        ),
    ]
