# Generated by Django 5.0.4 on 2024-04-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_noisestation_weather_remove_sleep_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noisestation',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='noisestation',
            name='lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='lon',
            field=models.FloatField(),
        ),
    ]
