# Generated by Django 5.0.4 on 2024-05-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_alter_noisestation_lat_alter_noisestation_lon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noise',
            fields=[
                ('noise_id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField(default=13.857139052152801)),
                ('lon', models.FloatField(default=100.48867194387923)),
                ('timestamp', models.DateTimeField()),
                ('noise', models.FloatField()),
                ('location_name', models.CharField(default='Nonthaburi', max_length=100)),
                ('region', models.CharField(default='Nonthaburi', max_length=100)),
                ('country', models.CharField(default='Thailand', max_length=100)),
                ('tz_id', models.CharField(default='Asia/Bangkok', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='NoiseStation',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='sleep_comments',
            new_name='sleep_comment',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='weather_api_id',
            new_name='weather_id',
        ),
        migrations.AddField(
            model_name='weather',
            name='country',
            field=models.CharField(default='Thailand', max_length=100),
        ),
        migrations.AddField(
            model_name='weather',
            name='location_name',
            field=models.CharField(default='Nonthaburi', max_length=100),
        ),
        migrations.AddField(
            model_name='weather',
            name='region',
            field=models.CharField(default='Nonthaburi', max_length=100),
        ),
        migrations.AddField(
            model_name='weather',
            name='tz_id',
            field=models.CharField(default='Asia/Bangkok', max_length=50),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='sleep_duration',
            field=models.FloatField(),
        ),
    ]
