<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-05-12 16:50
=======
# Generated by Django 5.0.4 on 2024-04-21 07:42
>>>>>>> c2db8309ae6545292eae70b18edde1813af68151

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_alter_noisestation_lat_alter_noisestation_lon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noise',
            fields=[
                ('noise_id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('noise', models.FloatField()),
                ('location_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('tz_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='NoiseStation',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='weather_api_id',
            new_name='weather_id',
        ),
        migrations.AddField(
            model_name='weather',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='location_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='tz_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
